#!/usr/bin/env node
/// <reference types="node" />
/**
 * Build AGENTS.md from the layered constitution files.
 *
 * Modes:
 *   build  - write AGENTS.md (default)
 *   check  - exit non-zero if AGENTS.md differs from regenerated output
 *
 * Sources (in order):
 *   - CLAUDE.md
 *   - .claude/engineering.md
 *   - .claude/workflow.md
 *   - .claude/stack.md
 *
 * See ADR-045 (cross-tool agents spine) for the rationale.
 */
import * as fs from "node:fs";
import * as path from "node:path";

const sources = [
  "CLAUDE.md",
  ".claude/engineering.md",
  ".claude/workflow.md",
  ".claude/stack.md",
] as const;

const output = "AGENTS.md";
const root = process.cwd();

function readSource(relPath: string): string {
  const abs = path.resolve(root, relPath);
  if (!fs.existsSync(abs)) {
    console.error(`❌ Source file missing: ${relPath}`);
    process.exit(1);
  }
  return fs.readFileSync(abs, "utf8");
}

/**
 * Demote every markdown ATX heading by one level, skipping fenced code blocks.
 * `# Foo` becomes `## Foo`, `## Bar` becomes `### Bar`, etc. H6 is left as-is
 * (markdown's max depth) to avoid producing invalid `#######` headings; no
 * source file currently uses H6.
 */
function demoteHeadings(md: string): string {
  const lines = md.split("\n");
  let inFence = false;
  return lines
    .map((line) => {
      if (line.startsWith("```")) {
        inFence = !inFence;
        return line;
      }
      if (inFence) {
        return line;
      }
      if (/^#{1,5} /.test(line)) {
        return `#${line}`;
      }
      return line;
    })
    .join("\n");
}

function buildAgentsMd(): string {
  const banner = [
    "<!--",
    "  AGENTS.md — Astro Performance Starter",
    "",
    "  GENERATED FILE — DO NOT EDIT DIRECTLY.",
    "  Regenerate with: pnpm agents:build",
    "  Drift gate:       pnpm agents:check (runs in quality:ci)",
    "",
    "  Sources (in order):",
    ...sources.map((s) => `    - ${s}`),
    "-->",
    "",
    "# AGENTS.md — Astro Performance Starter",
    "",
    "Cross-tool canonical context for AI agents working in this repo. Generated from the layered constitution: `CLAUDE.md` + `.claude/engineering.md` + `.claude/workflow.md` + `.claude/stack.md`. Tools that read `AGENTS.md` natively (Cursor, Codex CLI, Copilot, Windsurf, Aider, Devin, Zed, Continue) get the full constitution from this file. Claude Code reads the layered files directly via [`CLAUDE.md`](CLAUDE.md) and its Precedence clause; this file mirrors the same content.",
    "",
    "Do not edit this file directly. Edit the source file in the layer where the rule belongs (constitution in `CLAUDE.md`; engineering defaults in `.claude/engineering.md`; process and workflow in `.claude/workflow.md`; stack facts in `.claude/stack.md`) and run `pnpm agents:build`. CI fails if this file drifts from its sources (see [ADR-045](docs/adr/045-cross-tool-agents-spine.md)).",
    "",
  ].join("\n");

  const sections = sources.map((src) => demoteHeadings(readSource(src).trim()));
  return `${banner}\n${sections.join("\n\n")}\n`;
}

const mode = process.argv[2] ?? "build";

if (mode === "build") {
  const content = buildAgentsMd();
  const outPath = path.resolve(root, output);
  fs.writeFileSync(outPath, content, "utf8");
  console.log(
    `✅ Wrote ${output} (${content.split("\n").length} lines from ${sources.length} sources)`,
  );
  process.exit(0);
}

if (mode === "check") {
  const generated = buildAgentsMd();
  const outPath = path.resolve(root, output);
  if (!fs.existsSync(outPath)) {
    console.error(`❌ ${output} does not exist. Run \`pnpm agents:build\` and commit.`);
    process.exit(1);
  }
  const existing = fs.readFileSync(outPath, "utf8");
  if (existing !== generated) {
    console.error(`❌ ${output} is out of sync with its source files.`);
    console.error(`   Sources: ${sources.join(", ")}`);
    console.error(`   Run \`pnpm agents:build\` and commit the result.`);
    process.exit(1);
  }
  console.log(`✅ ${output} is in sync with source files.`);
  process.exit(0);
}

console.error(`❌ Unknown mode: ${mode}. Use 'build' or 'check'.`);
process.exit(1);
