#!/usr/bin/env node
// Simple token build script: converts tokens/base.json to Tailwind-ready JS module
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const root = dirname(new URL(import.meta.url).pathname.replace(/^\//, ""));
const basePath = join(root, "..", "tokens", "base.json");
const distDir = join(root, "..", "tokens", "dist");

// ensure dist dir
mkdirSync(distDir, { recursive: true });

const base = JSON.parse(readFileSync(basePath, "utf-8"));

const tailwindTokens = {
  colors: base.color || {},
  spacing: base.spacing || {},
  fontSize: base.fontSize || {},
  borderRadius: base.borderRadius || {},
  transitionDuration: base.motion?.duration || {},
};

const outFile = join(distDir, "tailwind-tokens.js");
writeFileSync(
  outFile,
  `// Auto-generated by scripts/build-tokens.js\nexport default ${JSON.stringify(tailwindTokens, null, 2)};\n`,
);

console.log("✅ Built Tailwind tokens ->", outFile);
