name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

      - name: Check all links with Lychee
        run: pnpm run check:links
